version: "3.9"
services:
  db:
    image: mysql:8.0.28
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock_example
      MYSQL_USER: admin
      MYSQL_PASSWORD: p@ssword
      TZ: Asia/Seoul
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379

# docker compose --build -up