version: "3.9"
services:
  db:
    image: mysql:8.0.28
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock_example
      MYSQL_USER: admin
      MYSQL_PASSWORD: p@ssword
      TZ: Asia/Seoul

# docker compose --build -up